# -*- coding: utf-8 -*-
from functools import partial
import re,requests
from datetime import datetime,timedelta
import sys
import Announce
from PyQt5.QtWidgets import QApplication, QMainWindow
# Form implementation generated from reading ui file 'Announce.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

def get_date(start_time_str,end_time_str):    #获取输入时间段内的日期
    dates=[]
    start_time = datetime.strptime(start_time_str,'%Y-%M-%d') #把字符串转化为日期
    end_time = datetime.strptime(end_time_str,'%Y-%M-%d')
    date_diff = (end_time - start_time).days   #计算日期差

    for i in range(date_diff + 1):
        data_date = start_time + timedelta(days=i)   #递增日期
        dates.append(data_date.strftime('%Y-%M-%d'))   #把日期增加到列表
    return dates

def get_cookies():   #登录接口获取cookies
    url = 'http://10.79.5.175:8080/dpas/doLogin'
    data = {"lt": "", "execution": "", "_eventId": "submit", "userLocale": "zh_CN", "username": "27380",
            "password": "123", "rememberMe": "true"}
    header = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "Referer": "http://10.79.5.175:8080/dpas/login"
    }
    r = requests.post(url=url,data=data,headers=header)
    res_cookie = r.headers['Set-Cookie']
    a = res_cookie.split(';')[0]
    b = res_cookie.split(';')[-6].split(',')[1][1:]
    cookie = a+';'+b
    return cookie
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 11, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 90, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 61, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 50, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 130, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 220, 451, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 10, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 10, 113, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 90, 113, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 90, 113, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 170, 113, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 250, 601, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Announce"))
        self.label.setText(_translate("MainWindow", "起始地："))
        self.label_2.setText(_translate("MainWindow", "目的地："))
        self.label_3.setText(_translate("MainWindow", "起始日期："))
        self.label_4.setText(_translate("MainWindow", "结束日期："))
        self.label_5.setText(_translate("MainWindow", "舱位："))
        self.label_6.setText(_translate("MainWindow", "地方请输入大写字母例如CAN"))
        self.label_7.setText(_translate("MainWindow", "日期输入2024-02-07格式"))
        self.label_8.setText(_translate("MainWindow", "1为头等舱，2为公务舱,3为明珠经济舱，4为经济舱"))
        self.pushButton.setText(_translate("MainWindow", "查询"))

    def common(self):
        resulr = ''
        try:
            departure = self.lineEdit.text()
            destination = self.lineEdit_2.text()
            start_time = self.lineEdit_3.text()
            end_time = self.lineEdit_4.text()
            listx = self.lineEdit_5.text()

            list1 = ['F']  # 头等舱
            list2 = ['J', 'C', 'D', 'I', 'O']  # 公务舱
            list3 = ['W', 'S']  # 明珠经济舱
            list4 = ['Y', 'P', 'B', 'M', 'H', 'K', 'U', 'A', 'L', 'Q', 'E', 'V', 'Z', 'T', 'N', 'R', 'G', 'X']  # 经济舱
            list5 = ['F', 'J', 'C', 'D', 'I', 'O', 'W', 'S', 'Y', 'P', 'B', 'M', 'H', 'K', 'U', 'A', 'L', 'Q', 'E', 'V',
                     'Z', 'T', 'N', 'R', 'G', 'X']

            date_1 = get_date(start_time, end_time)
            cookies = get_cookies()
            for z in range(len(date_1)):
                url_1 = 'http://10.79.5.175:8080/dpas/pages/publish/page'
                data_2 = {"params['departure']": departure, "params['destination']": destination,
                          "params['flightDate']": date_1[z],
                          "params['checkType']": "1", "page.pageNo": '1', "page.pageSize": '10'}
                hearder_1 = {"Accept": "text/html, */*; q=0.01", "Cookie": cookies,
                             "Referer": "http://10.79.5.175:8080/dpas/doLogin"}
                res = requests.get(url=url_1, params=data_2, headers=hearder_1)
                b = 'gn:middle;">(.*?)</td>'
                c = re.findall(b, res.text)
                list_cw = []
                list_m = []
                list_data = []
                for r in c:
                    try:
                        if r in list5:
                            list_cw.append(r)
                        list_m.append(int(r))
                    except:
                        pass

                for n in range(len(list_cw)):
                    list_data.append(list_cw[n] + ':' + str(list_m[n]))

                list_fina = []
                if listx == '1':
                    list_sel = list1
                elif listx == '2':
                    list_sel = list2
                elif listx == '3':
                    list_sel = list3
                elif listx == '4':
                    list_sel = list4
                elif listx == '5':
                    list_sel = list5

                for m in list_data:
                    if m[0] in list_sel:
                        list_fina.append(m[2:])

                for j in range(len(list_fina) - 1):
                    if int(list_fina[j]) > int(list_fina[j + 1]):
                        # resulr += 'pass\n'
                        pass

                    else:

                        resulr += '航段：' + departure + '-' + destination + ',日期：' + date_1[z] + ',' + str(
                            list_fina[j]) + '倒挂' + str(list_fina[j + 1])+'\n'
                        break
                if resulr == '':
                    resulr = '您查询的数据无倒挂'
                    self.plainTextEdit.setPlainText(str(resulr))
                else:
                    self.plainTextEdit.setPlainText(str(resulr))

        except Exception as e:
            print(e)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Announce.Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.pushButton.clicked.connect(partial(ui.common))
    MainWindow.show()
    sys.exit(app.exec_())
